<a href="https://colab.research.google.com/github/JapiKredi/Pinnacle_AI_program_AnalyticsVidyha/blob/main/4_Modifying_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

---
---

<center><h1>üìç üìç Modifying Data üìç üìç</h1></center>

---


### `TABLE OF CONTENTS`

- How to impute the missing values in any column?
- How to update the values of a column with a new mapping?
- How to create a new column by modifying the existing column?
- How to convert categorical variables into numerical?

---

####  `READ THE DATA`


- In this notebook, we are going to use the big mart sales data that we have used previously. It is stored in the folder name `datasets`.

---

In [1]:
# importing the pandas library
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
# read the dataset
data = pd.read_csv('/content/drive/My Drive/Pandas_ModifyingData/datasets/big_mart_sales.csv')

In [4]:
# view the top rows of the data
data.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

---

#### `HOW TO IMPUTE THE MISSING VALUES USING LOC IN ANY COLUMN?`


***Check the columns with null values.***

First, we will check the number of missing values in each of the column. Use the function `isna().sum()`.



---

In [5]:
# check for the null values
data.isna().sum()

Item_Identifier                 0
Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

So, we have missing values in the column `Item_Weight` and `Outlet_Size`.

---

#### `Select the columns where Item_Weight has missing values using loc`

---

In [6]:
# rows with null values in the Item_Weight
data.loc[data.Item_Weight.isna() == True]

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
7,FDP10,NaN,Low Fat,0.127470,Snack Foods,107.7622,OUT027,1985,Medium,Tier 3,Supermarket Type3,4022.7636
18,DRI11,NaN,Low Fat,0.034238,Hard Drinks,113.2834,OUT027,1985,Medium,Tier 3,Supermarket Type3,2303.6680
21,FDW12,NaN,Regular,0.035400,Baking Goods,144.5444,OUT027,1985,Medium,Tier 3,Supermarket Type3,4064.0432
23,FDC37,NaN,Low Fat,0.057557,Baking Goods,107.6938,OUT019,1985,Small,Tier 1,Grocery Store,214.3876
29,FDC14,NaN,Regular,0.072222,Canned,43.6454,OUT019,1985,Small,Tier 1,Grocery Store,125.8362
...,...,...,...,...,...,...,...,...,...,...,...,...
8485,DRK37,NaN,Low Fat,0.043792,Soft Drinks,189.0530,OUT027,1985,Medium,Tier 3,Supermarket Type3,6261.8490
8487,DRG13,NaN,Low Fat,0.037006,Soft Drinks,164.7526,OUT027,1985,Medium,Tier 3,Supermarket Type3,4111.3150
8488,NCN14,NaN,Low Fat,0.091473,Others,184.6608,OUT027,1985,Medium,Tier 3,Supermarket Type3,2756.4120
8490,FDU44,NaN,Regular,0.102296,Fruits and Vegetables,162.3552,OUT019,1985,Small,Tier 1,Grocery Store,487.3656
8504,NCN18,NaN,Low Fat,0.124111,Household,111.7544,OUT027,1985,Medium,Tier 3,Supermarket Type3,4138.6128

In [7]:
data.Item_Weight.mean()

12.857645184135976

In [8]:
# fill the null values in Item_Weight by mean
data.loc[(data.Item_Weight.isna() == True) , 'Item_Weight'] = data.Item_Weight.mean()

In [9]:
data.isna().sum()

Item_Identifier                 0
Item_Weight                     0
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [10]:
data.dtypes

Item_Identifier               object
Item_Weight                  float64
Item_Fat_Content              object
Item_Visibility              float64
Item_Type                     object
Item_MRP                     float64
Outlet_Identifier             object
Outlet_Establishment_Year      int64
Outlet_Size                   object
Outlet_Location_Type          object
Outlet_Type                   object
Item_Outlet_Sales            float64
dtype: object

In [11]:
data.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

#### `Fill the missing values in the column: Outlet_Size by most frequent value using loc`

---

***Mode of Outlet Size***

In [12]:
data.Outlet_Size.mode()

0    Medium
Name: Outlet_Size, dtype: object

In [13]:
data.Outlet_Size.value_counts()

Outlet_Size
Medium    2793
Small     2388
High       932
Name: count, dtype: int64

In [14]:
data.loc[(data.Outlet_Size.isna() == True) , 'Outlet_Size'] = 'Medium'

#### `Use the fillna function to impute the missing values.`

- `fillna` function is another way to impute the missing values. Use the parameter `inplace=True` to store the results in the dataframe.

In [15]:
# fill the null values in Outlet Size by the most frequent value: "Medium"
data.Outlet_Size.fillna('Medium', inplace=True)

<ipython-input-15-c7248f05920d>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data.Outlet_Size.fillna('Medium', inplace=True)

In [16]:
# check the null values again
data.isna().sum()

Item_Identifier              0
Item_Weight                  0
Item_Fat_Content             0
Item_Visibility              0
Item_Type                    0
Item_MRP                     0
Outlet_Identifier            0
Outlet_Establishment_Year    0
Outlet_Size                  0
Outlet_Location_Type         0
Outlet_Type                  0
Item_Outlet_Sales            0
dtype: int64

#### `HOW TO UPDATE THE VALUES OF A COLUMN?`


---

In [17]:
# look at the data
data.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,Medium,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

---

***Let's have a look at the count of each category in the column `Item_Fat_Content`. We will use `value_counts` function to to do that.***


---

In [18]:
data.Item_Fat_Content.value_counts()

Item_Fat_Content
Low Fat    5089
Regular    2889
LF          316
reg         117
low fat     112
Name: count, dtype: int64

---

***We can see that the categories `Low Fat`, `LF` and `low fat` are same and also `Regular`, `reg` are same. So to keep the data clean we will map all these to only two categories to `LF` and `R` using the map function. Let's see how?***

In [19]:
# Create a new mapping (dictionary)
mapping = {
    'Low Fat' : 'LF',
    'Regular' : 'R',
    'LF' : 'LF',
    'reg': 'R',
    'low fat' : 'LF'
}

In [20]:
data.Item_Fat_Content.map(mapping)

0       LF
1        R
2       LF
3        R
4       LF
        ..
8518    LF
8519     R
8520    LF
8521     R
8522    LF
Name: Item_Fat_Content, Length: 8523, dtype: object

In [21]:
# use the  map function to update the values
data.Item_Fat_Content = data.Item_Fat_Content.map(mapping)

In [22]:
# Count of new categories in the column Item_Fat_Content
data.Item_Fat_Content.value_counts()

Item_Fat_Content
LF    5517
R     3006
Name: count, dtype: int64

#### `HOW TO CREATE A NEW COLUMN BY MODIFYING THE EXISTING COLUMN?`

---

In [ ]:
data.Item_MRP

0       249.8092
1        48.2692
2       141.6180
3       182.0950
4        53.8614
          ...
8518    214.5218
8519    108.1570
8520     85.1224
8521    103.1332
8522     75.4670
Name: Item_MRP, Length: 8523, dtype: float64

#### `APPLY`

***Create a new column `Item_MRP_in_USD` by dividing the each value in the column `Item_MRP` by 74 using the apply function. Let's see how?***

---

In [23]:
data.Item_MRP.apply(lambda x: x/74)

0       3.375800
1       0.652286
2       1.913757
3       2.460743
4       0.727857
          ...
8518    2.898943
8519    1.461581
8520    1.150303
8521    1.393692
8522    1.019824
Name: Item_MRP, Length: 8523, dtype: float64

In [30]:
data['Item_MRP_in_USD'] = data.Item_MRP.apply(lambda x : x/74)

In [31]:
data.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,Item_MRP_in_USD_UPDATED,Item_MRP_in_USD
0,FDA15,9.30,LF,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380,4.655800,3.375800
1,DRC01,5.92,R,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228,1.932286,0.652286
2,FDN15,17.50,LF,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700,3.193757,1.913757
3,FDX07,19.20,R,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,Medium,Tier 3,Grocery Store,732.3800,3.740743,2.460743
4,NCD19,8.93,LF,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052,2.007857,0.727857

In [25]:
def convert(price):
    price = price/74
    price = price + 1.28
    return price

In [26]:
data['Item_MRP_in_USD_UPDATED'] = data.Item_MRP.apply(lambda x : convert(x))

In [27]:
data.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,Item_MRP_in_USD_UPDATED
0,FDA15,9.30,LF,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380,4.655800
1,DRC01,5.92,R,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228,1.932286
2,FDN15,17.50,LF,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700,3.193757
3,FDX07,19.20,R,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,Medium,Tier 3,Grocery Store,732.3800,3.740743
4,NCD19,8.93,LF,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052,2.007857

In [32]:
data[['Item_MRP','Item_MRP_in_USD']]

      Item_MRP  Item_MRP_in_USD
0     249.8092         3.375800
1      48.2692         0.652286
2     141.6180         1.913757
3     182.0950         2.460743
4      53.8614         0.727857
...        ...              ...
8518  214.5218         2.898943
8519  108.1570         1.461581
8520   85.1224         1.150303
8521  103.1332         1.393692
8522   75.4670         1.019824

[8523 rows x 2 columns]

---

#### `HOW TO CONVERT CATEGORICAL VARIABLES INTO NUMERICAL?`

Most of the machine learning algorithms do not take categorical variables so we need to convert them into numerical ones. In pandas, we have one such function `get_dummies` which will help us in doing such tasks.  It will create a binary column for each of the categories.

For example, look at the image below, We have two genders male and female. It will create two binary columns.  
![](encode.png)

This is also known as `One Hot Encoding`. You will learn more encoding techniques in the data pre-processing module.

---

#### Let's look at the data again.

In [33]:
data.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,Item_MRP_in_USD_UPDATED,Item_MRP_in_USD
0,FDA15,9.30,LF,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380,4.655800,3.375800
1,DRC01,5.92,R,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228,1.932286,0.652286
2,FDN15,17.50,LF,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700,3.193757,1.913757
3,FDX07,19.20,R,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,Medium,Tier 3,Grocery Store,732.3800,3.740743,2.460743
4,NCD19,8.93,LF,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052,2.007857,0.727857

In [34]:
# currently we have 13 columns in the data
data.shape

(8523, 14)

#### `USE GET_DUMMIES`

---

In [35]:
# convert categorical variables into numerical variables.
data = pd.get_dummies(data)

In [36]:
# view the data
data.head()

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Establishment_Year,Item_Outlet_Sales,Item_MRP_in_USD_UPDATED,Item_MRP_in_USD,Item_Identifier_DRA12,Item_Identifier_DRA24,Item_Identifier_DRA59,...,Outlet_Size_High,Outlet_Size_Medium,Outlet_Size_Small,Outlet_Location_Type_Tier 1,Outlet_Location_Type_Tier 2,Outlet_Location_Type_Tier 3,Outlet_Type_Grocery Store,Outlet_Type_Supermarket Type1,Outlet_Type_Supermarket Type2,Outlet_Type_Supermarket Type3
0,9.30,0.016047,249.8092,1999,3735.1380,4.655800,3.375800,False,False,False,...,False,True,False,True,False,False,False,True,False,False
1,5.92,0.019278,48.2692,2009,443.4228,1.932286,0.652286,False,False,False,...,False,True,False,False,False,True,False,False,True,False
2,17.50,0.016760,141.6180,1999,2097.2700,3.193757,1.913757,False,False,False,...,False,True,False,True,False,False,False,True,False,False
3,19.20,0.000000,182.0950,1998,732.3800,3.740743,2.460743,False,False,False,...,False,True,False,False,False,True,True,False,False,False
4,8.93,0.000000,53.8614,1987,994.7052,2.007857,0.727857,False,False,False,...,True,False,False,False,False,True,False,True,False,False

In [37]:
# now, we have 1603 columns
data.shape

(8523, 1604)